/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nickk.mehralent;
import java.awt.HeadlessException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author nick
 */
public class main_login extends javax.swing.JFrame {

    /**
     * Creates new form main_login
     */
    public main_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uidtf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pwdtf = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login or Die...");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Please enter your name :");

        jLabel2.setText("Password Please :");

        jButton1.setText("LOGIN");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("DIE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uidtf)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(pwdtf))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uidtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(35, 35, 35))
        );

        setSize(new java.awt.Dimension(472, 307));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainClass mc = new MainClass();
        // Declare Vars
        String u,p;
        u = uidtf.getText();
        p = new String (pwdtf.getPassword());
        try{
            Class.forName(mc.cl);
            Connection con = DriverManager.getConnection(mc.url,mc.user,mc.pwd);
            Statement stmt = con.createStatement();
            String q ;
            q = "Select * from login_records;";
            ResultSet rs = stmt.executeQuery(q);
            if (rs.next()==true){
                String u2g,p2g;
                u2g = rs.getString("U_Id");
                p2g = rs.getString("U_Pass");
                // Get encrypting :P
                String passwordToHash = p;
                String realpass =null;
             try{
                 MessageDigest md = MessageDigest.getInstance("MD5");
                 md.update(passwordToHash.getBytes());
                 byte[] bytes = md.digest();
                 StringBuilder sb = new StringBuilder();
                 for (int i = 0; i<bytes.length;i++){
                 sb.append(Integer.toString((bytes [i] & 0xff) + 0x100,16).substring(1));
                 }
                 realpass = sb.toString();
                  System.out.println(realpass);
             }
             catch (NoSuchAlgorithmException e){
                String ee = e.getMessage();
                JOptionPane.showMessageDialog(this,ee);
             }
                if (u.equals(u2g) && p2g.equals(realpass)){
                   JOptionPane.showMessageDialog(this,"Welcome "+u.toUpperCase());
                   System.out.println("It is "+realpass);
                   dispose();
                   new activity_chooser().setVisible(true);
               }
               else{
               JOptionPane.showMessageDialog(this,"Sorry, Try Again!");
               uidtf.setText(null);pwdtf.setText(null);
               uidtf.requestFocus();
               }
            }
            else {
            JOptionPane.showMessageDialog(this,"Sir, I Don't think there are any users yet");
            uidtf.requestFocus();
            }
        }
        catch (ClassNotFoundException | SQLException | HeadlessException e ){
            String ee = e.getMessage();
            JOptionPane.showMessageDialog(this,ee);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // I am an egoistic bastard so i will integrate product activation wizard.
        // Here 401 for not activated, 402 for blocked, 403 for access, 404 for not found
        MainClass mc = new MainClass();
        try{
            Class.forName(mc.cl);
            Connection con = DriverManager.getConnection(mc.url,mc.user,mc.pwd);
            Statement stmt = con.createStatement();
            String q;
            q = "Select * from integrity_records";
            ResultSet rs = stmt.executeQuery(q);
            if (rs.next()== true){
                String fet = rs.getString("curr_status");
                if (fet.equals("401")){
                    int a;
                    a = JOptionPane.showConfirmDialog(this,"Thanks for purchasing, Activate Now?","Activation Request",JOptionPane.YES_NO_OPTION);
                    if (a == JOptionPane.YES_OPTION){
                        dispose();
                        new product_activation().setVisible(true);
                    }
                }
                else if (fet.equals("402")){
                     JOptionPane.showConfirmDialog(this,"Product has been blocked, Contact Admin!","Contact/Unblock?",JOptionPane.YES_NO_OPTION);
                }
                else if (fet.equals("403")){
                     JOptionPane.showMessageDialog(this,"Welcome to Mehrals Software v1.0");
                     jButton1.setEnabled(true);
                }
                else if (fet.equals("404")){
                    JOptionPane.showMessageDialog(this,"No users found!, Creating Users!");
                    dispose();
                    new user_creator().setVisible(true);
                }
                else {
                     JOptionPane.showMessageDialog(this,"This computer seems crazy, Call Doctor!");
                }
            }
            // JOptionPane.showMessageDialog(this,"Someone rightly said, Don't Ever Steal!","Resurrect?",JOptionPane.WARNING_MESSAGE);
            }
        catch (Exception e){
            
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField pwdtf;
    private javax.swing.JTextField uidtf;
    // End of variables declaration//GEN-END:variables
}
